# Generated by Django 3.2.7 on 2021-10-27 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_price', models.IntegerField(default=0)),
                ('prod_description', models.CharField(default='', max_length=200)),
                ('prod', models.ImageField(upload_to='produsts/')),
            ],
        ),
        migrations.DeleteModel(
            name='AdminLogin',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='c_item_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='c_usr_id',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
