# Generated by Django 3.2.7 on 2021-10-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_auto_20211027_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod',
            new_name='prod_image',
        ),
        migrations.AddField(
            model_name='product',
            name='prod_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.category'),
        ),
    ]
